# low
fold: 0
n_epochs: 1
img_sz: 640       # 512, 640, 768, ....
folder: 'effdet5_weights' # folder where are the model checkpoints & log files will be saved.

# medium
lr: 0.0002
num_workers: 2
batch_size: 1
accumulation_steps: 4  # Gradient Accumulation
mixed_precision: False # turn ON apex.amp (Automatic Mixed Precision)

# high 
dev: False
verbose: False
verbose_step: 1

step_scheduler: False       # do scheduler.step after optimizer.step
validation_scheduler: True  # do scheduler.step after validation stage loss